/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gradingsystem;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jawar
 */
public class AddingStudents extends javax.swing.JFrame {

    /**
     * Creates new form AddingStudents
     */
    
    
    PreparedStatement ps = null;
    Connection con = null;
    ResultSet rs = null;
    
    public AddingStudents() {
        initComponents();
        
        tf_curriculum.setForeground(new Color(51,51,51));
        con = DbConnection.getStdConnection();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tf_level = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        tf_nameOfStudent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _addStdUser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(78, 80, 82));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_level.setBackground(new java.awt.Color(204, 204, 204));
        tf_level.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(tf_level, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 220, 40));

        tf_id.setBackground(new java.awt.Color(204, 204, 204));
        tf_id.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 220, 40));

        tf_nameOfStudent.setBackground(new java.awt.Color(204, 204, 204));
        tf_nameOfStudent.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(tf_nameOfStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 220, 40));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("LEVEL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 40));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 40));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NAME OF THE STUDENT");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 40));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CURRICULUM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 40));

        tf_curriculum.setBackground(new java.awt.Color(51, 51, 51));
        tf_curriculum.setForeground(new java.awt.Color(204, 204, 204));
        tf_curriculum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "REGULAR", "IRREGULAR" }));
        jPanel2.add(tf_curriculum, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 220, 40));

        _addStdUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        _addStdUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _addStdUser.setText("ADD STUDENTS");
        jPanel2.add(_addStdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 20, 460, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 46, 470, 420));

        jButton1.setBackground(new java.awt.Color(122, 160, 203));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("ADD");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 130, 40));

        b_cancel.setBackground(new java.awt.Color(255, 119, 112));
        b_cancel.setForeground(new java.awt.Color(51, 51, 51));
        b_cancel.setText("CANCEL");
        b_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_cancelMouseClicked(evt);
            }
        });
        jPanel1.add(b_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 480, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String _id = tf_id.getText();
        String _nameOfStudent = tf_nameOfStudent.getText();
        String _level = tf_level.getText();
        String _curriculum = (String)tf_curriculum.getSelectedItem();
        
        DbConnection dc = new DbConnection();
        dc.creatingDb();
        dc.creatingTableForAdding();
        dc.insertingDbInAddingStd(_id, _nameOfStudent, _level, _curriculum);
        dc.creatingTableForStudent(_id);
        
        
        Object[] options = { "YES", "NO" };
        Object selectedValue = JOptionPane.showOptionDialog(null, "Student " + _nameOfStudent + " is now added. You still want to add more student?", "Who knows...",
        JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
        null, options, options[0]); 

        System.out.println(selectedValue);

        if(selectedValue.equals(1))
        {
            this.setVisible(false);
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void b_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_cancelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddingStudents().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _addStdUser;
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private final javax.swing.JComboBox<String> tf_curriculum = new javax.swing.JComboBox<>();
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_level;
    private javax.swing.JTextField tf_nameOfStudent;
    // End of variables declaration//GEN-END:variables
}
