/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gradingsystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author jawar
 */
public class UserAdminEditor extends javax.swing.JFrame {

    /**
     * Creates new form UserAdminEditor
     */
    
     Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    
    static final String DB_URL = "jdbc:mysql://localhost/sgs_administrator";
    static final String USER = "root";
    static final String PASS = "";
    public UserAdminEditor() {
        initComponents();
        con = DbConnection.getConnection();
        
        
    }
    
    
     public void closeThisForm()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_Username = new javax.swing.JTextField();
        b_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_Password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        tf_Password1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 230, 40));

        b_login.setBackground(new java.awt.Color(255, 119, 112));
        b_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b_login.setForeground(new java.awt.Color(0, 0, 0));
        b_login.setText("SIGN UP");
        b_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_loginMouseClicked(evt);
            }
        });
        jPanel1.add(b_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 230, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADDING USER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 470, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("USERNAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 40));

        tf_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 230, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/x_.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 60, 50));

        tf_Password1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(tf_Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 230, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("REPEAT PASSWORD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_loginMouseClicked
        // TODO add your handling code here:
        String usrname = tf_Username.getText();
        String psword = String.valueOf(tf_Password.getPassword());
        String psword1 = String.valueOf(tf_Password1.getPassword());
        
         if(usrname.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Username filed is empty!");        
        }
        else if(psword.equalsIgnoreCase(""))
        {
             JOptionPane.showMessageDialog(null, "Password filed is empty!"); 
        }
        else if(!psword1.equalsIgnoreCase(psword))
        {
            JOptionPane.showMessageDialog(null, "Different value of password");
            System.out.println(psword + " " + psword1);
        }
         else
        {
            DbConnection dc = new DbConnection();
            try {
                
                dc.creatingAdminDb();
                dc.creatingTableForAdmin();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Sorry I can't access you to the Database, please contact your developer");
            }
             try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
         Statement stmt = conn.createStatement();
      ) {
                    
                    dc.creatingTableForAdding();
        
                    System.out.println("Inserting new user into the table...");          
                    String sql = "INSERT INTO admin (username, password) VALUES ('"+usrname + "', '"+ psword1+"')";
                    stmt.executeUpdate(sql);

                    JOptionPane.showMessageDialog(null, "Successfully created new admin");
      } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Sorry I can't access you to the Database, please contact your developer");
      } 
        }

       
    }//GEN-LAST:event_b_loginMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdminEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdminEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdminEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdminEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserAdminEditor().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JPasswordField tf_Password1;
    private javax.swing.JTextField tf_Username;
    // End of variables declaration//GEN-END:variables
}
